spring.application.name=doctools


server.address=0.0.0.0
server.port=8080

#app.base-url=http://localhost:8080
app.base-url=http://192.168.29.112:8080

# Database URL (Default port is 5432)
spring.datasource.url=jdbc:postgresql://localhost:5432/doctools
spring.datasource.username=airflow
spring.datasource.password=airflow

# JPA/Hibernate Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

# FILE CONFIG (CRITICAL)
file.upload-dir=uploads/
file.output-dir=outputs/